name: min_id
description: >-
  ID generator for dart easily like eat ðŸ¥®ðŸ¥®ðŸ¥®ðŸ¥®.
  You can generate unique string, unique number, unique any thing by min_id ðŸ‘.
version: 1.1.0
homepage: https://github.com/tvc12/min_id
repository: https://github.com/tvc12/min_id
documentation: https://github.com/tvc12/min_id
issue_tracker: https://github.com/tvc12/min_id/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: 1.16.8
  pedantic: 1.11.0
